lang: zh-Hans
title: 能哥网
email: m@nenge.net
description: >- # this means to ignore newlines until "baseurl:"
  懵逼树下懵逼的你和我.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nenge123
github_username:  nenge123

url:        	 http://localhost:4000
#baseurl:     /
#url:         http://localhost:4000
# Owner/author information
page:
  title: ""
  description: ""
# Build settings
timezone:    Asia/ShangHai
future:      true
highlighter: rouge
markdown:    kramdown
paginate:    5
paginate_path: "page:num"
#theme: minima
sass:
    sass_dir: assets/sass
    style: compressed

permalink: /article/:year:month:day/:title.html

plugins: [jekyll-paginate]

plugins_dir:
- jemoji
- jekyll-paginate

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
